services:
  app:
    image: "ghcr.io/frankmarazita/q:latest"
    container_name: q-server
    network_mode: host
    command: "bun run index.ts serve --port ${PORT}"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      SENTRY_DSN: ${SENTRY_DSN}
    restart: on-failure:5
